site_name: Everyday Blog
site_url: https://rollingmountains.github.io/blog/
repo_url: https://github.com/rollingmountains/blog

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - toc.integrate
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: indigo
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: indigo
      accent: indigo

plugins:
  - blog:
      post_dir: 'articles'
      # meta: false
      # post_url_date_prefix: false
      # post_excerpt: 'optional'
      # post_excerpt_separator: '<!-- more -->'
      # post_exclude: []
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      fallback_to_build_date: true
      exclude:
        - blog/archive/.*
        - blog/category/.*
        - blog/.*\.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourusername

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - attr_list
  - toc:
      permalink: true