site_name: Everyday Blog
site_url: https://rollingmountains.github.io/blog/
# repo_url: https://github.com/rollingmountains/blog


theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.sticky
    - navigation.path
    - toc.integrate
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: indigo
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: indigo
      accent: indigo

nav:
  - Home: index.md
  - Programming: programming/index.md
  - Life: life/index.md
  - About: about.md

plugins:
  - blogging:
  # {{ blog_content }}
      dirs: 
      - posts
  # {{ blog_content <category name> }}
      categories:
        - name: programming
          dirs: 
            - posts/programming 
          size: 5  
          theme:
            name: card
        - name: life
          dirs: 
            - posts/life
          size: 5
          theme:
            name: card



      features:
        tag: {}
      # post_excerpt: 'optional'
      # meta: true
      # post_url_date_prefix: false
      # post_excerpt_separator: '<!-- more -->'
      # post_exclude: []
      # locale: en
      # blog_toc: true
      # categories_toc: true
      # categories_slugify: true
      # categories_case_sensitive: false
      # Add this to sort posts by date
      # blog_sort_default: desc
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      fallback_to_build_date: true
      exclude:
        - blog/archive/.*
  # - macros

# extra:
  # social:
  #   - icon: fontawesome/brands/github
  #     link: https://github.com/yourusername
  #   - icon: fontawesome/brands/twitter
  #     link: https://twitter.com/yourusername

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - attr_list
  - toc:
      permalink: true

extra_css:
  - assets/styles.css